- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
      cloud: ospcloud
      server: 'frontend'
    register: openstack_info

  - name: Curl website
    command: curl "http://{{item.public_v4}}"
    with_items:
       - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
  - name: Fail
    fail:
    when: "'Ansible' not in webpage.results[0].stdout" 
